apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-flugelit
  name: wp-flugelit
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wp-flugelit